name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: dariusf/pandoc-publish@master
    - uses: actions/upload-artifact@master
      with:
        name: oct-wave.pdf
        path: build/pdf/oct-wave.pdf
    - uses: actions/upload-artifact@master
      with:
        name: oct-wave.epub
        path: build/epub/oct-wave.epub
